# ReVanced build with Anddea patches (dev branch)
# Builds: YouTube, YouTube Music (arm64-v8a, APK + Magisk)

enable-magisk-update = true
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"
cli-version = "latest"
rv-brand = "ReVanced Extended"
remove-rv-integrations-checks = false

[YouTube]
app-name = "YouTube"
enabled = true
build-mode = "both"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
module-prop-name = "youtube"
excluded-patches = "'Hide shortcuts'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'MaterialYou' -e 'Custom branding icon for YouTube' -OappIcon=xisr_winter -e 'Custom header for YouTube' -OcustomHeader=custom_branding_icon -e 'Settings for YouTube' -OrvxSettingsLabel='ReVanced Extended Settings'"

[YouTubeMusic]
app-name = "YouTube Music"
enabled = true
build-mode = "both"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
module-prop-name = "youtube-music"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'MaterialYou'"
